#############################################################################
# Makefile for building: iqrf_ide
# Generated by qmake (2.01a) (Qt 4.4.0) on: Mon Sep 7 22:10:08 2009
# Project:  iqrf_ide.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile iqrf_ide.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtGui -I/usr/include/QtDBus -I/usr/include/QtDBus -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtDBus -L/usr/lib -L/lib -ldbus-1 -lQtXml -lQtGui -L/usr/X11R6/lib -lpng -lSM -lICE -lXi -lXrender -lXrandr -lXfixes -lXcursor -lXinerama -lfreetype -lfontconfig -lXext -lX11 -lQtCore -lz -lm -lrt -ldl -lpthread -lusb
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		programmer.cpp \
		hex_parser.cpp \
		setup_dialog.cpp \
		compile_dialog.cpp \
		core/iqrf_dev.cpp \
		core/lusb.cpp \
		core/spi.cpp moc_mainwindow.cpp \
		moc_setup_dialog.cpp \
		moc_compile_dialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		programmer.o \
		hex_parser.o \
		setup_dialog.o \
		compile_dialog.o \
		iqrf_dev.o \
		lusb.o \
		spi.o \
		moc_mainwindow.o \
		moc_setup_dialog.o \
		moc_compile_dialog.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		iqrf_ide.pro
QMAKE_TARGET  = iqrf_ide
DESTDIR       = 
TARGET        = iqrf_ide

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_setup_dialog.h ui_compile_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: iqrf_ide.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtDBus.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtCore.prl \
		/usr/lib/libQtGui.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile iqrf_ide.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtDBus.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtCore.prl:
/usr/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile iqrf_ide.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/iqrf_ide1.0.0 || $(MKDIR) .tmp/iqrf_ide1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/iqrf_ide1.0.0/ && $(COPY_FILE) --parents mainwindow.h programmer.h lusb.h hex_parser.h setup_dialog.h compile_dialog.h core/iqrf_dev.h core/lusb.h core/spi.h .tmp/iqrf_ide1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp programmer.cpp hex_parser.cpp setup_dialog.cpp compile_dialog.cpp core/iqrf_dev.cpp core/lusb.cpp core/spi.cpp .tmp/iqrf_ide1.0.0/ && $(COPY_FILE) --parents mainwindow.ui setup_dialog.ui compile_dialog.ui .tmp/iqrf_ide1.0.0/ && (cd `dirname .tmp/iqrf_ide1.0.0` && $(TAR) iqrf_ide1.0.0.tar iqrf_ide1.0.0 && $(COMPRESS) iqrf_ide1.0.0.tar) && $(MOVE) `dirname .tmp/iqrf_ide1.0.0`/iqrf_ide1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/iqrf_ide1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_setup_dialog.cpp moc_compile_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_setup_dialog.cpp moc_compile_dialog.cpp
moc_mainwindow.cpp: programmer.h \
		iqrf_dev.h \
		lusb.h \
		spi.h \
		hex_parser.h \
		compile_dialog.h \
		setup_dialog.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_setup_dialog.cpp: setup_dialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) setup_dialog.h -o moc_setup_dialog.cpp

moc_compile_dialog.cpp: compile_dialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) compile_dialog.h -o moc_compile_dialog.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all: ui_mainwindow.h ui_setup_dialog.h ui_compile_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_setup_dialog.h ui_compile_dialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_setup_dialog.h: setup_dialog.ui
	/usr/bin/uic setup_dialog.ui -o ui_setup_dialog.h

ui_compile_dialog.h: compile_dialog.ui
	/usr/bin/uic compile_dialog.ui -o ui_compile_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		programmer.h \
		iqrf_dev.h \
		lusb.h \
		spi.h \
		hex_parser.h \
		compile_dialog.h \
		setup_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		programmer.h \
		iqrf_dev.h \
		lusb.h \
		spi.h \
		hex_parser.h \
		compile_dialog.h \
		setup_dialog.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

programmer.o: programmer.cpp programmer.h \
		iqrf_dev.h \
		lusb.h \
		spi.h \
		hex_parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o programmer.o programmer.cpp

hex_parser.o: hex_parser.cpp hex_parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hex_parser.o hex_parser.cpp

setup_dialog.o: setup_dialog.cpp setup_dialog.h \
		ui_setup_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setup_dialog.o setup_dialog.cpp

compile_dialog.o: compile_dialog.cpp compile_dialog.h \
		ui_compile_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compile_dialog.o compile_dialog.cpp

iqrf_dev.o: core/iqrf_dev.cpp iqrf_dev.h \
		lusb.h \
		spi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iqrf_dev.o core/iqrf_dev.cpp

lusb.o: core/lusb.cpp core/lusb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lusb.o core/lusb.cpp

spi.o: core/spi.cpp spi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spi.o core/spi.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_setup_dialog.o: moc_setup_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setup_dialog.o moc_setup_dialog.cpp

moc_compile_dialog.o: moc_compile_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_compile_dialog.o moc_compile_dialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

